### ISSUE TITLE
Eagle again, eh?

### ISSUE THREAD

**Issue by pfalcon** [domino-team/domino-hardware#1]
I remember you replying that you don't have need/time to learn e.g. Kicad if Eagle works for you. "Glad" to see that even a kickstarter is not a reason for you do more homework with OpenSource tools.

Way to go, OpenHardware community! Aka shame-shame-shame ;-)

P.S. And yes, I keep saying this, because next time when in low spirit I reach for a proprietary crap, someone else shamed myself into doing the right thing.

**Comment by Squonk42** [comment]
Sorry, but I tried again recently, and KiCAD is missing many important points and still segfaulting very often.

I have been working with many ECAD suites (Orcad, Protel Altiium, PCAD), and I can't used to KiCAD's counter-intuitive part managment, bad translations, random menus, etc.

At least ERC and back-annotation should work, which is apparently not the case.
