### ISSUE TITLE
Correct way to attribute the PCB design

### ISSUE THREAD

**Issue by pastcompute** [domino-team/domino-hardware#2]
Hi,

I'm looking at designing a shield PCB for the Domino Pi, for which I would like to copy the pinout stencil layer.

What is your preferred text to conform with the CC4 license?

I'm guessing something like the following printed on the stencil layer would suffice

```
Licensed under a Creative Commons
Attribution-Share-Alike Unported License.
See creativecommons.org/licenses/by-sa/4.0/

Attribution: portions of this design, specifically, the pinout stencil, (c) 2014-2015 The Domino Team (http://domino.io)
```

**Comment by Squonk42** [comment]
This is fine if you have enough real room to put all this text, but you may also jsut provide a URI or hyperlink to a resource that includes the required information, see http://creativecommons.org/licenses/by-sa/4.0/legalcode, section 3.a.2.

**Comment by pastcompute** [comment]
No worries. I was more asking as to how to refer to yourselves, so I guess that wherever it lives, attribution to (c) 2014-2015 The Domino Team (http://domino.io) conveys all the necessary information
