### ISSUE TITLE
Domino Pi CP2104 USB UART not working?

### ISSUE THREAD

**Issue by gruvin** [domino-team/domino-hardware#3]
Hello

I received my first Domino Pi from the Kickstarter campaign, today. It's working nicely. Great work!

However, it seems that the Silicon Labs CP2104 USB UART device is not working. I have the OS X drivers installed and use several other devices via CP210x chips. But in this case, no serial ports appear on OS X (/dev/tty.blah) or even in the raw USB devices, 'System Report' for that matter.

**Is this a known issue** or do I perhaps have a faulty Domino Pi board? If the latter, then perhaps I should see about checking the solder joints on the CP2104 chip, etc? I am tooled up and fine with that tiny SMD stuff. But would rather not risk damage until I get an answer here.

Thanks! :-)

Bryan.

**Comment by alzhao** [comment]
The usb uart bridge should work. It rarely faulty. Is it possible that you
try on Windows or Linux first to see what is happening?

**Comment by gruvin** [comment]
Thanks for the answer, @alzhao. Astonishingly, after a full inspection under the microscope and some continuity testing, etc ... it turned out simply to be TWO faulty USB micro cables! All working now. Yay \o/

~~This issue should now be closed. I don't appear to have to do that.~~

Bryan

**Comment by gruvin** [comment]
Alas and perhaps not surprisingly, I did NOT have two faulty cables, after all. The SP2104 chip is only coming online as a valid USB device about one in five times I plug it in. Otherwise, it is not being recognised even at the lowest hardware level -- as if nothing was physically plugged in at all.

There doesn't appear to be any dry joints. I guess I must have a dud chip, somehow. Guess I'll order some in, replace it and see what happens.

**Comment by gruvin** [comment]
OK. I finally got to the bottom of it.

Pint 9 (/RST) on the CP2014 was being held almost low by a low resistance semi-bridge in the solder beneath the chip. This appears to have come about due to the pads for both pin 9 and 10 being physically missing (peeled up off the board, by the looks) causing both pins to semi attach to the solder on the large, square ground plane under the chip, during solder re-flow.

It took two remove and replace cycles of the chip for me to figure this out. Initially, I removed the chip, cleaned everything up and reinstalled. It seemed to work for about a half hour. Then the problem returned. Looking closer at things directly after removing it a second time, there was evidence suggesting a possible short of pin 9 to GND. I took steps to avoid that happening again on my second re-install and re-flow. Now, touch wood!, everything is working fine.

**NOTE** I would recommend moving the via just inside of pin 2 a few mils further away from pin 2. The drill for the via pushed the via's surrounding track very close to pin 1 - well under 3 mil spacing in my case. Avoiding that potential short seems an easy fix for future versions.

**Also**, I think you should add an external pull-up to pin 9, even though it's not supposed to be required. Extra noise immunity is always good around RF transmissions! :-)

Anyway. A lot to do about very little. But there it is, in case anyone finds it useful.

Bryan.

**Comment by Squonk42** [comment]
Hi @gruvin,

Thanks for spotting this! Nice hardware debugging.

Pads 9 and 10 are not supposed to be missing, and adding a pull-up to pin 9 is a very good suggestion.

We tried to put the via on pin 2 this close in order to avoid this via "sucking" solder from the large square central pad. But the last-minute "teardrop" added by the corresponding EagleCAD script made it such that it is barely respecting the 6 mils clearance rule. We will fix it in future revision.
